# Generated by Django 3.2.3 on 2021-08-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basket_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
