# Generated by Django 2.0 on 2021-08-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_created',
        ),
    ]
