# Generated by Django 3.2.3 on 2021-08-04 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_shopuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_created',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 21, 22, 18, 620213, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='о се бе'),
        ),
    ]
